Feature MySQL database optimizations
miketvo/rmit-isys2099-group9-app pull request #49
Opened 2023-09-01 08:12 UTC by miketvo

# Changes:

- As we have discussed, to save time, we will remove the feature for products to have images. I dropped this column from the product table. Remember to adjust accordingly on your BE @LaansDole and on your FE @DeathHunterX.
- Added indices for the most important tables that will have a lot of rows in the future if our application is deployed:
    - `warehouse`
    - `product`
    - `inbound_order`
    - `buyer_order`

See `database/mysql/init/indexing.sql` for documentation and reasoning @nhattran1206.

## Remember to refresh your local database with the following steps:

1. From the project's root directory, navigate to `database/mysql/` directory:
   ```bash
   cd database/mysql
   ```
2. Initialize the MySQL database:
   ```bash
   npm ci
   npm run setup-with-mock-data  # You will be prompted for your MySQL server root username and password
   ```

2023-09-01 08:20 UTC, nhattran1206 submitted a review, later dismissed
Thank you @miketvo. LGTM

2023-09-04 02:29 UTC, LaansDole requested changes
Don't delete the image mock-data yet

2023-09-04 02:44 UTC, miketvo commented
> Don't delete the image mock-data yet

Finally have your feedback. Alright, I'll add them back, but do you also want to add the `image` column back to the `product` table @LaansDole?

2023-09-04 03:01 UTC, LaansDole approved these changes

2023-09-04 03:01 UTC, nhattran1206 approved these changes

2023-09-04 03:02 UTC, DeathHunterX approved these changes

2023-09-04 03:04 UTC, merged